apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  mysql-root-password: cm9vdA==        # base64 of "root"
  mysql-database: Zmxhc2tsb2dpbg==     # base64 of "flasklogin"
